/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaisyklesRouteImport } from './routes/taisykles'
import { Route as PrivatumoPolitikaRouteImport } from './routes/privatumo-politika'
import { Route as KontaktaiRouteImport } from './routes/kontaktai'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as AuthenticatedAdminLinksRouteImport } from './routes/_authenticated.admin.links'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated.admin.leads'
import { Route as ApiPublicQrTokenRouteImport } from './routes/api/public/qr.$token'
import { Route as AuthenticatedAdminLinksTokenRouteImport } from './routes/_authenticated.admin.links.$token'
import { Route as AuthenticatedAdminBatchesNewRouteImport } from './routes/_authenticated.admin.batches.new'
import { Route as AuthenticatedAdminBatchesIdRouteImport } from './routes/_authenticated.admin.batches.$id'
import { Route as AuthenticatedAdminLinksTokenQrRouteImport } from './routes/_authenticated.admin.links.$token.qr'

const TaisyklesRoute = TaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumoPolitikaRoute = PrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktaiRoute = KontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminLinksRoute = AuthenticatedAdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicQrTokenRoute = ApiPublicQrTokenRouteImport.update({
  id: '/api/public/qr/$token',
  path: '/api/public/qr/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminLinksTokenRoute =
  AuthenticatedAdminLinksTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => AuthenticatedAdminLinksRoute,
  } as any)
const AuthenticatedAdminBatchesNewRoute =
  AuthenticatedAdminBatchesNewRouteImport.update({
    id: '/batches/new',
    path: '/batches/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBatchesIdRoute =
  AuthenticatedAdminBatchesIdRouteImport.update({
    id: '/batches/$id',
    path: '/batches/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLinksTokenQrRoute =
  AuthenticatedAdminLinksTokenQrRouteImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AuthenticatedAdminLinksTokenRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontaktai': typeof KontaktaiRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/taisykles': typeof TaisyklesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/r/$token': typeof RTokenRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/links': typeof AuthenticatedAdminLinksRouteWithChildren
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/batches/$id': typeof AuthenticatedAdminBatchesIdRoute
  '/admin/batches/new': typeof AuthenticatedAdminBatchesNewRoute
  '/admin/links/$token': typeof AuthenticatedAdminLinksTokenRouteWithChildren
  '/api/public/qr/$token': typeof ApiPublicQrTokenRoute
  '/admin/links/$token/qr': typeof AuthenticatedAdminLinksTokenQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontaktai': typeof KontaktaiRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/taisykles': typeof TaisyklesRoute
  '/admin/login': typeof AdminLoginRoute
  '/r/$token': typeof RTokenRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/links': typeof AuthenticatedAdminLinksRouteWithChildren
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/batches/$id': typeof AuthenticatedAdminBatchesIdRoute
  '/admin/batches/new': typeof AuthenticatedAdminBatchesNewRoute
  '/admin/links/$token': typeof AuthenticatedAdminLinksTokenRouteWithChildren
  '/api/public/qr/$token': typeof ApiPublicQrTokenRoute
  '/admin/links/$token/qr': typeof AuthenticatedAdminLinksTokenQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/kontaktai': typeof KontaktaiRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/taisykles': typeof TaisyklesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/r/$token': typeof RTokenRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/links': typeof AuthenticatedAdminLinksRouteWithChildren
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/batches/$id': typeof AuthenticatedAdminBatchesIdRoute
  '/_authenticated/admin/batches/new': typeof AuthenticatedAdminBatchesNewRoute
  '/_authenticated/admin/links/$token': typeof AuthenticatedAdminLinksTokenRouteWithChildren
  '/api/public/qr/$token': typeof ApiPublicQrTokenRoute
  '/_authenticated/admin/links/$token/qr': typeof AuthenticatedAdminLinksTokenQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontaktai'
    | '/privatumo-politika'
    | '/taisykles'
    | '/admin'
    | '/admin/login'
    | '/r/$token'
    | '/admin/leads'
    | '/admin/links'
    | '/api/public/leads'
    | '/admin/'
    | '/admin/batches/$id'
    | '/admin/batches/new'
    | '/admin/links/$token'
    | '/api/public/qr/$token'
    | '/admin/links/$token/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontaktai'
    | '/privatumo-politika'
    | '/taisykles'
    | '/admin/login'
    | '/r/$token'
    | '/admin/leads'
    | '/admin/links'
    | '/api/public/leads'
    | '/admin'
    | '/admin/batches/$id'
    | '/admin/batches/new'
    | '/admin/links/$token'
    | '/api/public/qr/$token'
    | '/admin/links/$token/qr'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/kontaktai'
    | '/privatumo-politika'
    | '/taisykles'
    | '/_authenticated/admin'
    | '/admin/login'
    | '/r/$token'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/links'
    | '/api/public/leads'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/batches/$id'
    | '/_authenticated/admin/batches/new'
    | '/_authenticated/admin/links/$token'
    | '/api/public/qr/$token'
    | '/_authenticated/admin/links/$token/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  KontaktaiRoute: typeof KontaktaiRoute
  PrivatumoPolitikaRoute: typeof PrivatumoPolitikaRoute
  TaisyklesRoute: typeof TaisyklesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicQrTokenRoute: typeof ApiPublicQrTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taisykles': {
      id: '/taisykles'
      path: '/taisykles'
      fullPath: '/taisykles'
      preLoaderRoute: typeof TaisyklesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktai': {
      id: '/kontaktai'
      path: '/kontaktai'
      fullPath: '/kontaktai'
      preLoaderRoute: typeof KontaktaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/links': {
      id: '/_authenticated/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AuthenticatedAdminLinksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/qr/$token': {
      id: '/api/public/qr/$token'
      path: '/api/public/qr/$token'
      fullPath: '/api/public/qr/$token'
      preLoaderRoute: typeof ApiPublicQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/links/$token': {
      id: '/_authenticated/admin/links/$token'
      path: '/$token'
      fullPath: '/admin/links/$token'
      preLoaderRoute: typeof AuthenticatedAdminLinksTokenRouteImport
      parentRoute: typeof AuthenticatedAdminLinksRoute
    }
    '/_authenticated/admin/batches/new': {
      id: '/_authenticated/admin/batches/new'
      path: '/batches/new'
      fullPath: '/admin/batches/new'
      preLoaderRoute: typeof AuthenticatedAdminBatchesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/batches/$id': {
      id: '/_authenticated/admin/batches/$id'
      path: '/batches/$id'
      fullPath: '/admin/batches/$id'
      preLoaderRoute: typeof AuthenticatedAdminBatchesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/links/$token/qr': {
      id: '/_authenticated/admin/links/$token/qr'
      path: '/qr'
      fullPath: '/admin/links/$token/qr'
      preLoaderRoute: typeof AuthenticatedAdminLinksTokenQrRouteImport
      parentRoute: typeof AuthenticatedAdminLinksTokenRoute
    }
  }
}

interface AuthenticatedAdminLinksTokenRouteChildren {
  AuthenticatedAdminLinksTokenQrRoute: typeof AuthenticatedAdminLinksTokenQrRoute
}

const AuthenticatedAdminLinksTokenRouteChildren: AuthenticatedAdminLinksTokenRouteChildren =
  {
    AuthenticatedAdminLinksTokenQrRoute: AuthenticatedAdminLinksTokenQrRoute,
  }

const AuthenticatedAdminLinksTokenRouteWithChildren =
  AuthenticatedAdminLinksTokenRoute._addFileChildren(
    AuthenticatedAdminLinksTokenRouteChildren,
  )

interface AuthenticatedAdminLinksRouteChildren {
  AuthenticatedAdminLinksTokenRoute: typeof AuthenticatedAdminLinksTokenRouteWithChildren
}

const AuthenticatedAdminLinksRouteChildren: AuthenticatedAdminLinksRouteChildren =
  {
    AuthenticatedAdminLinksTokenRoute:
      AuthenticatedAdminLinksTokenRouteWithChildren,
  }

const AuthenticatedAdminLinksRouteWithChildren =
  AuthenticatedAdminLinksRoute._addFileChildren(
    AuthenticatedAdminLinksRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminLinksRoute: typeof AuthenticatedAdminLinksRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBatchesIdRoute: typeof AuthenticatedAdminBatchesIdRoute
  AuthenticatedAdminBatchesNewRoute: typeof AuthenticatedAdminBatchesNewRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminLinksRoute: AuthenticatedAdminLinksRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBatchesIdRoute: AuthenticatedAdminBatchesIdRoute,
  AuthenticatedAdminBatchesNewRoute: AuthenticatedAdminBatchesNewRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  KontaktaiRoute: KontaktaiRoute,
  PrivatumoPolitikaRoute: PrivatumoPolitikaRoute,
  TaisyklesRoute: TaisyklesRoute,
  AdminLoginRoute: AdminLoginRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicQrTokenRoute: ApiPublicQrTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
