/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router.
// It is committed because hosts may type-check before regenerating routes.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as AuthenticatedAdminImport } from './routes/_authenticated.admin'
import { Route as AdminLoginImport } from './routes/admin.login'
import { Route as ApiPublicLeadsImport } from './routes/api/public/leads'
import { Route as ApiPublicQrTokenImport } from './routes/api/public/qr.$token'
import { Route as IndexImport } from './routes/index'
import { Route as KontaktaiImport } from './routes/kontaktai'
import { Route as PrivatumoPolitikaImport } from './routes/privatumo-politika'
import { Route as RTokenImport } from './routes/r.$token'
import { Route as TaisyklesImport } from './routes/taisykles'
import { Route as AuthenticatedAdminBatchesIdImport } from './routes/_authenticated.admin.batches.$id'
import { Route as AuthenticatedAdminBatchesNewImport } from './routes/_authenticated.admin.batches.new'
import { Route as AuthenticatedAdminIndexImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminLeadsImport } from './routes/_authenticated.admin.leads'
import { Route as AuthenticatedAdminLinksImport } from './routes/_authenticated.admin.links'
import { Route as AuthenticatedAdminLinksTokenImport } from './routes/_authenticated.admin.links.$token'
import { Route as AuthenticatedAdminLinksTokenQrImport } from './routes/_authenticated.admin.links.$token.qr'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAdminRoute = AuthenticatedAdminImport.update({
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AdminLoginRoute = AdminLoginImport.update({
  path: '/admin/login',
  getParentRoute: () => rootRoute,
} as any)

const ApiPublicLeadsRoute = ApiPublicLeadsImport.update({
  path: '/api/public/leads',
  getParentRoute: () => rootRoute,
} as any)

const ApiPublicQrTokenRoute = ApiPublicQrTokenImport.update({
  path: '/api/public/qr/$token',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const KontaktaiRoute = KontaktaiImport.update({
  path: '/kontaktai',
  getParentRoute: () => rootRoute,
} as any)

const PrivatumoPolitikaRoute = PrivatumoPolitikaImport.update({
  path: '/privatumo-politika',
  getParentRoute: () => rootRoute,
} as any)

const RTokenRoute = RTokenImport.update({
  path: '/r/$token',
  getParentRoute: () => rootRoute,
} as any)

const TaisyklesRoute = TaisyklesImport.update({
  path: '/taisykles',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedAdminBatchesIdRoute = AuthenticatedAdminBatchesIdImport.update({
  path: '/batches/$id',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedAdminBatchesNewRoute = AuthenticatedAdminBatchesNewImport.update({
  path: '/batches/new',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsImport.update({
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedAdminLinksRoute = AuthenticatedAdminLinksImport.update({
  path: '/links',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedAdminLinksTokenRoute = AuthenticatedAdminLinksTokenImport.update({
  path: '/links/$token',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

const AuthenticatedAdminLinksTokenQrRoute = AuthenticatedAdminLinksTokenQrImport.update({
  path: '/qr',
  getParentRoute: () => AuthenticatedAdminLinksTokenRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginImport
      parentRoute: typeof rootRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsImport
      parentRoute: typeof rootRoute
    }
    '/api/public/qr/$token': {
      id: '/api/public/qr/$token'
      path: '/api/public/qr/$token'
      fullPath: '/api/public/qr/$token'
      preLoaderRoute: typeof ApiPublicQrTokenImport
      parentRoute: typeof rootRoute
    }
    '/kontaktai': {
      id: '/kontaktai'
      path: '/kontaktai'
      fullPath: '/kontaktai'
      preLoaderRoute: typeof KontaktaiImport
      parentRoute: typeof rootRoute
    }
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaImport
      parentRoute: typeof rootRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenImport
      parentRoute: typeof rootRoute
    }
    '/taisykles': {
      id: '/taisykles'
      path: '/taisykles'
      fullPath: '/taisykles'
      preLoaderRoute: typeof TaisyklesImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/admin/batches/$id': {
      id: '/_authenticated/admin/batches/$id'
      path: '/batches/$id'
      fullPath: '/admin/batches/$id'
      preLoaderRoute: typeof AuthenticatedAdminBatchesIdImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/admin/batches/new': {
      id: '/_authenticated/admin/batches/new'
      path: '/batches/new'
      fullPath: '/admin/batches/new'
      preLoaderRoute: typeof AuthenticatedAdminBatchesNewImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/admin/links': {
      id: '/_authenticated/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AuthenticatedAdminLinksImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/admin/links/$token': {
      id: '/_authenticated/admin/links/$token'
      path: '/links/$token'
      fullPath: '/admin/links/$token'
      preLoaderRoute: typeof AuthenticatedAdminLinksTokenImport
      parentRoute: typeof AuthenticatedAdminImport
    }
    '/_authenticated/admin/links/$token/qr': {
      id: '/_authenticated/admin/links/$token/qr'
      path: '/qr'
      fullPath: '/admin/links/$token/qr'
      preLoaderRoute: typeof AuthenticatedAdminLinksTokenQrImport
      parentRoute: typeof AuthenticatedAdminLinksTokenImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedAdminRoute: AuthenticatedAdminRoute.addChildren({
      AuthenticatedAdminBatchesIdRoute,
      AuthenticatedAdminBatchesNewRoute,
      AuthenticatedAdminIndexRoute,
      AuthenticatedAdminLeadsRoute,
      AuthenticatedAdminLinksRoute,
      AuthenticatedAdminLinksTokenRoute: AuthenticatedAdminLinksTokenRoute.addChildren({
        AuthenticatedAdminLinksTokenQrRoute,
      }),
    }),
  }),
  AdminLoginRoute,
  ApiPublicLeadsRoute,
  ApiPublicQrTokenRoute,
  IndexRoute,
  KontaktaiRoute,
  PrivatumoPolitikaRoute,
  RTokenRoute,
  TaisyklesRoute,
})

/* prettier-ignore-end */
